theme: jekyll-theme-minimal
title: Winter School
description: A beginner's guide to historical network research with Python hosted by the "[DH Lab](https://dhlab.hypotheses.org)" of the "[IEG](https://www.ieg-mainz.de/en/research/digital_historical_research/introduction)"
