theme: jekyll-theme-minimal
title: Winter School - A beginner's guide to historical network research
description: Introduction to historical network analysis with Python hosted by the <a href="https://dhlab.hypotheses.org" target="_blank">DH Lab</a> of the <a href = "https://www.ieg-mainz.de/en/research/digital_historical_research/introduction">IEG</a>.
